import { chromium } from 'playwright';
import path from 'path';
const file = 'file://' + path.resolve('dist/awuu.html');
const shots = process.env.SHOTS || 'test-shots';
import('fs').then((fs) => fs.mkdirSync(shots, { recursive: true }));
const vw = +(process.env.VW || 390), vh = +(process.env.VH || 844);
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: vw, height: vh }, hasTouch: true, isMobile: true });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message + '\n' + e.stack));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto(file);
await page.waitForTimeout(2000);
const tag = process.env.TAG || 'p';
await page.screenshot({ path: `${shots}/${tag}-title.png` });
await page.evaluate(() => document.getElementById('btnSkins').click());
await page.waitForTimeout(2500);
await page.screenshot({ path: `${shots}/${tag}-skins.png` });
await page.evaluate(() => document.querySelector('#scrSkins [data-back]').click());
await page.waitForTimeout(300);
await page.evaluate(() => document.getElementById('btnAlbum').click());
await page.waitForTimeout(500);
await page.screenshot({ path: `${shots}/${tag}-album.png` });
await page.evaluate(() => document.querySelector('#scrAlbum [data-back]').click());
await page.evaluate(() => document.getElementById('btnSettings').click());
await page.waitForTimeout(500);
await page.screenshot({ path: `${shots}/${tag}-settings.png` });
await page.evaluate(() => document.querySelector('#scrSettings [data-back]').click());
await page.evaluate(() => document.getElementById('btnPlay').click());
await page.waitForTimeout(400);
await page.screenshot({ path: `${shots}/${tag}-levels.png` });
await page.evaluate(() => document.querySelectorAll('.lcard')[0].click());
await page.waitForTimeout(1200);
await page.screenshot({ path: `${shots}/${tag}-intro.png` });
await page.evaluate(() => document.getElementById('btnStart').click());
await page.waitForTimeout(3400);
// real touch on joystick zone
const cdp = await page.context().newCDPSession(page);
const sx = 90, sy = vh - 140;
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: sx, y: sy, id: 1 }] });
for (let i = 0; i < 20; i++) {
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: sx + 40, y: sy - 50 - i, id: 1 }] });
  await page.waitForTimeout(80);
}
const moved = await page.evaluate(() => { const g = window.__awuu.game; return { inp: [g.inp.mx, g.inp.mz], moved: g.wolf.moved, pos: g.wolf.body.pos.toArray() }; });
console.log('TOUCH', JSON.stringify(moved));
await page.screenshot({ path: `${shots}/${tag}-play-touch.png` });
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
// tap jump button
const jb = await page.evaluate(() => { const r = document.getElementById('btnJump').getBoundingClientRect(); return [r.x + r.width / 2, r.y + r.height / 2]; });
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: jb[0], y: jb[1], id: 2 }] });
await page.waitForTimeout(400);
const air = await page.evaluate(() => { const g = window.__awuu.game; return { jumps: g.stats.jumps, state: g.state }; });
const hit = await page.evaluate(([x, y]) => { const e = document.elementFromPoint(x, y); return e && (e.id || e.className); }, jb);
console.log('HIT', hit, jb);
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
console.log('JUMP registered', JSON.stringify(air));
// pause + free mode quit flow
await page.evaluate(() => document.getElementById('btnPause').click());
await page.waitForTimeout(400);
await page.screenshot({ path: `${shots}/${tag}-pause.png` });
await page.evaluate(() => document.getElementById('btnQuit').click());
await page.waitForTimeout(500);
await page.evaluate(() => document.getElementById('btnFree').click());
await page.waitForTimeout(300);
await page.evaluate(() => document.querySelectorAll('.lcard')[0].click());
await page.waitForTimeout(800);
await page.evaluate(() => document.getElementById('btnStart').click());
await page.waitForTimeout(3500);
await page.evaluate(() => { document.getElementById('btnPause').click(); });
await page.waitForTimeout(200);
await page.evaluate(() => { document.getElementById('btnQuit').click(); });
await page.waitForTimeout(800);
await page.screenshot({ path: `${shots}/${tag}-free-result.png` });
console.log(errors.length ? errors.slice(0, 8).join('\n') : 'no errors');
await browser.close();
